"""empty message

Revision ID: 58d15b5107e4
Revises: 
Create Date: 2025-02-05 15:06:50.699788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d15b5107e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('publisher', sa.String(length=50), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('videos', sa.Text(), nullable=True),
    sa.Column('thumbnails', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('appid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
